# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ef97c0d17f66a640cefba7424758eedc7f7cae351e84d02ffc79872d40754baa0afba6ef1f75f5d987c1c30478429d20ad8b543f58b14844512891adc54abe5

test:
  secret_key_base: 9c25006b564fe33bd19832dbe30430b7e9b409966db4b25846ca647026b012ab52a3e4cef4568ae545ba603d83aee47634dabd0293067f26fc3e202ac084c4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
